export enum Channel {
    MOUSE_CLICK,
    
    REDRAW_CELL,
    REDRAW_CELLS,
    REDRAW_ALL_CELLS,
    DESELECT_ALL_CELLS,
    
    LEGAL_MOVES_CALCULATED,
    
    GAME_STATE_PIECE_SELECTED,
    GAME_STATE_MOVE_PIECE,
    GAME_STATE_SAVE,
    GAME_STATE_LOAD
}